### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [ilyakurdyukov/fpdoom#1]
Hello!

I found this project from https://www.opennet.me/opennews/art.shtml?num=58397

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by ilyakurdyukov** [comment]
I don't know what should be the license for material obtained by reverse engineering. It's kind of a gray area. Consider it a copyleft.

**Comment by vazhnov** [comment]
@ilyakurdyukov , if there are some pieces of your code, you can mention that these pieces are distributed, for example, under MIT license or GPL v2+.
Also, you can use SPDX headers to highlight opensource files: https://spdx.dev/resources/use/

**Comment by ilyakurdyukov** [comment]
Are you satisfied with the Unlicense?

**Comment by vazhnov** [comment]
Yes, Unlicense is amazing!
@ilyakurdyukov , thank you very much!
