### ISSUE TITLE
New tested device

### ISSUE THREAD

**Issue by wiors** [ilyakurdyukov/fpdoom#3]
Please add to the list of tested models this one: Vertex D514
CPU - sc6531e
LCD: idk, but all works fine, if it needs, i can attach a mark from lcd, resolution 240x320
Boot key - center button

**Comment by ilyakurdyukov** [comment]
The log shows the LCD model, here is from F+ F256:

```
BSL_REP_VER: "SPRD3\0"
BSL_REP_VER: "Custom FDL1: CHIP ID = 0x65620001\0"
!!! doom_init
malloc heap: 3719992 bytes
scan_firmware: 303ms
keymap = 0x10084b10
pinmap = 0x10080eec
chip_id: num = 0x65620001
chip_id: ver = 0xa0002
chip_id: ahb = 0x609
chip_id: adi = 0x1161a000
LCD: clk_rate = 104000000
LCD: id = 0x009306
!!! doom_main
DOOM Shareware Startup - v1.10
```

In the log 0x6562xxxx means SC6531E, SC6531DA (and compatible) is 0x6531xxxx.

I will update the table along with the update on other model.
