### ISSUE TITLE
Add GalaxyCore GC032A (Id 0x9306)

### ISSUE THREAD

**Issue by marohinmark** [ilyakurdyukov/fpdoom#4]
Please add GC032A 240x320 display panel support (Fly TS114). Phone's boot key is unknown, I was holding all keys on the keyboard at once.  Display is detected with --spi 1

**Comment by marohinmark** [comment]
Setting id to 0x9306 wont work, it exists in lcd_config.h though

**Comment by marohinmark** [comment]
This device id and model can be also found in engineering menu, so im 100% sure it's 0x9306

**Comment by ilyakurdyukov** [comment]
The SPI mode is the most difficult to do, it has many different settings.

I need firmware for this phone to see how it initializes, I still can't guarantee success.

You can also try `--spi 1 --spi_mode N --lcd 0x9306` (n = 1..4, default 3).
