### ISSUE TITLE
Fly TS114, unknown LCD even when passing --lcd 0x9306. any ideas how to fix? 

### ISSUE THREAD

**Issue by marohinmark** [ilyakurdyukov/fpdoom#5]
Display is detected only with --spi 1. LCD id found in engineering menu,

**Comment by marohinmark** [comment]
Boot key unknown.

**Comment by ilyakurdyukov** [comment]
The SPI mode is the most difficult to do, it has many different settings.

I need firmware for this phone to see how it initializes, I still can't guarantee success.

You can also try `--spi 1 --spi_mode N --lcd 0x9306` (n = 1..4, default 3).

What is `chip_id: num = 0x` in the log?

**Comment by marohinmark** [comment]
0x65620001

**Comment by marohinmark** [comment]
the cpu is sc6531e btw

**Comment by marohinmark** [comment]
I can send flash.bin I dumped, firmware for this phone is paid

**Comment by ilyakurdyukov** [comment]
> 0x65620001

So it's SC6531E, that's good, it has simpler SPI mode than SC6531DA (0x6531xxxx).

As you can see, SC6531E is a marketing name, in fact it is a different chip (6562) in the manufacturer's numbering.

**Comment by marohinmark** [comment]
is flash.bin somewhat useful or is pac file needed?

**Comment by ilyakurdyukov** [comment]
> I can send flash.bin I dumped, firmware for this phone is paid

You can mail me to jpegqs at gmail dot com.

**Comment by ilyakurdyukov** [comment]
> is flash.bin somewhat useful or is pac file needed?

I don't need .pac.

**Comment by ilyakurdyukov** [comment]
Judging by the firmware, the boot key is the right soft key. This is the key above the power key.

**Comment by marohinmark** [comment]
Btw, how exactly do you analyze the fw?

**Comment by ilyakurdyukov** [comment]
> Btw, how exactly do you analyze the fw?

Through unpacking ([bzpwork](https://github.com/ilyazx/bzpwork) or [uniflash](https://gitlab.com/suborg/uniflash)) and disassembly (architecture is armv5tej).
