### ISSUE TITLE
Nokia 6310 Dual sim tested, also having hard time booting it on TA-1174.

### ISSUE THREAD

**Issue by BedrockDotWebp** [ilyakurdyukov/fpdoom#7]
I tried booting up FPDoom on a Nokia 6310 DS (Nokia TA-1400) (Unisoc SC6531F), but that's all I got:

Test version 1.20230513:
> Waiting for connection (300s)
BSL_REP_VER: "Spreadtrum Boot Block version 1.2\0"
BSL_REP_VER: "Custom FDL1: CHIP ID = 0x65620001\0"
!!! entry1
malloc heap: 7917884 bytes
scan_firmware: 205ms
keymap = 0x10194934
pinmap = 0x10190e5c
chip_id: num = 0x65620001
chip_id: ver = 0xa0002
chip_id: ahb = 0xd09
chip_id: adi = 0x1161a000
LCD: clk_rate = 104000000
LCD: id = 0x000000
!!! unknown LCD
!!! exit(1)

And yes: the boot key is right soft key (above the power button (that's a bit too obvious though)). And if you need a FW dump, I'll send it.

**Comment by ilyakurdyukov** [comment]
Have you use `end_data 0` command as needed for Nokia TA-1174?

Try adding `--spi 1 --spi_mode 1` to the `libc_server` options, like this:

`$ cd workdir && ../libc_server -- --bright 50 --rotate 3 --spi 1 --spi_mode 1 doom`

Also try without `--spi_mode 1`, just `--spi 1`.

But even if the LCD is detected (`LCD: id=0x000000` will not be zero), it is unlikely that I have the config for that LCD, Nokia seems to use untypical LCDs for their phones.

You can send me the dump to jpegqs at gmail dot com.

**Comment by BedrockDotWebp** [comment]
I'm proudly sending it.

**Comment by BedrockDotWebp** [comment]
> Waiting for connection (300s)
BSL_REP_VER: "Spreadtrum Boot Block version 1.2\0"
BSL_REP_VER: "Custom FDL1: CHIP ID = 0x65620001\0"
!!! entry1
malloc heap: 7917884 bytes
scan_firmware: 205ms
keymap = 0x10194934
pinmap = 0x10190e5c
chip_id: num = 0x65620001
chip_id: ver = 0xa0002
chip_id: ahb = 0xd09
chip_id: adi = 0x1161a000
LCD: clk_rate = 104000000
LCD(SPI1): id = 0x9290f6
!!! unknown LCD
!!! exit(1)

It shows this w/ --spi 1, but w/ spi_mode 1, the LCD ID is 00ff90 :-\
as well as trying it w/ TA-1174, it just won't work...

**Comment by ilyakurdyukov** [comment]
> LCD(SPI1): id = 0x9290f6

This seems right.

I've seen 0x00ff00 as an invalid code.

> So, do different phone revisions have different LCDs as that's kinda strange?

One phone revision may support several LCD models from different vendors, display resolution is the same.

Some phones connect the LCD in an uncommon way, "--spi" options are for this.

> for my TA-1174, it shows 0x7c80f3

The version of TA-1174 I came across had LCD ID 0x1c80f3.

Try `--spi 1 --spi_mode 1 --lcd 0x1c80f3`, will it work?

**Comment by BedrockDotWebp** [comment]
it kinda works, because:
> Waiting for connection (300s)
BSL_REP_VER: "Spreadtrum Boot Block version 1.2\0"
BSL_REP_VER: "Custom FDL1: CHIP ID = 0x65620001\0"
!!! entry1
malloc heap: 3723580 bytes
scan_firmware: 36ms
!!! keymap not found
pinmap = 0x10029a7c
chip_id: num = 0x65620001
chip_id: ver = 0xa0002
chip_id: ahb = 0xd01
chip_id: adi = 0x1161a000
LCD: clk_rate = 104000000
!!! entry2
DOOM Registered Startup - v1.10
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
Z_Init: Init zone memory allocation daemon.
W_Init: Init WADfiles.
 adding doom.wad
===========================================================================
                 Commercial product - do not distribute!
         Please report software piracy to the SPA: 1-800-388-PIR8
===========================================================================
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon..
InitTextures
InitFlats........
InitSprites
InitColormaps
R_InitData
R_InitPointToAngle
R_InitTables
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables
P_Init: Init Playloop state.
Error: R_TextureNumForName: SW1BLUE not found
!!! exit(-1)

It can't find a texture. I used DOOM1.WAD from shareware version. And the LCD doesn't light up also.

**Comment by BedrockDotWebp** [comment]
Okay. Now TA-1174 lights up w/ registered DOOM.WAD that's sized 11MB.

**Comment by ilyakurdyukov** [comment]
> > for my TA-1174, it shows 0x7c80f3
> 
> The version of TA-1174 I came across had LCD ID 0x1c80f3. It could be the same LCD, but manufactured in a different factory.
> 
> Try `--spi 1 --spi_mode 1 --lcd 0x1c80f3`, will it work?

Oh, I see that it is indeed the same LCD, the name is "Sitronix ST7735", but from a different factory, I saw this LCD ID on another phone (Vector M115).

> It can't find a texture. I used DOOM1.WAD from shareware version. And the LCD doesn't light up also.

If you are using Linux then rename "DOOM1.WAD" to "doom1.wad". It should be in the "workdir" folder.

**Comment by BedrockDotWebp** [comment]
I use Windows, and WAD has filename fully in lowercase. So it's clearly compatibility issue from doom1.wad (shareware).

**Comment by ilyakurdyukov** [comment]
> I use Windows, and WAD has filename fully in lowercase. So it's clearly compatibility issue from doom1.wad (shareware).

This [doom1.wad](http://distro.ibiblio.org/pub/linux/distributions/slitaz/sources/packages/d/doom1.wad) works for me.

**Comment by BedrockDotWebp** [comment]
on my phone, it won't work (errors out at missing texture).
The registered 11MB WAD works no problem.

**Comment by ilyakurdyukov** [comment]
> on my phone, it won't work (errors out at missing texture). The registered 11MB WAD works no problem.

It's strange because it works for me and no one else has complained. It looks like a bug, but I don't know what it is related to.

**Comment by BedrockDotWebp** [comment]
It looks like it, but would be cool if I could run the game on Nokia 6310 DS, which I have, so this is mainly why I sent this issue w/ Nokia 6310 DS boot results.

**Comment by ilyakurdyukov** [comment]
It'll take some time to analyze the firmware. I'll write when I have some results.

**Comment by ilyakurdyukov** [comment]
I sent you a test build by email.

**Comment by BedrockDotWebp** [comment]
Okay, I'm downloading it.

**Comment by BedrockDotWebp** [comment]
Alright, so now, it boots up on TA-1400 :-) and more thorough testing is needed just in case.
![image](https://github.com/ilyakurdyukov/fpdoom/assets/144620948/40e8c705-7996-4a97-aa80-3bcaa8ddb7a9)

**Comment by BedrockDotWebp** [comment]
Since it's now working, this issue can be closed as complete.

**Comment by BedrockDotWebp** [comment]
and also, thank you @ilyakurdyukov  for making DOOM work on this phone ;-)

**Comment by ilyakurdyukov** [comment]
I'll make an update, LCD will work for your phones, but the `--spi` options will still be needed.

**Comment by BedrockDotWebp** [comment]
Okay

**Comment by ilyakurdyukov** [comment]
You can try the new version from [Releases](https://github.com/ilyakurdyukov/fpdoom/releases) (Duke3D and Shadow Warrior builds have also been updated). You don't need the `--lcd` option as in the test build.

Only these:

TA-1174: `--spi 1 --spi_mode 1`
TA-1400: `--spi 1`

> I do understand it'd work on my TA-1400, but not on others as they'd have different LCD controller/LCD revisions.

I added the configs of all supported LCDs (there's five) for this model that I found in the firmware.

And added an alias for TA-1174, 0x7c80f3 -> 0x1c80f3.
